# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dd9a434ee4c3cd743754e73df83c3f3f5aee833a8fdfa5f10dd834fb097150385663918e8c2f658c59b6675c0ae873437b270745b6926c49178b8b29e47a02c

test:
  secret_key_base: 8881b97e42ee1fec5c8a634e0a63231fbb8b6936348327f4d466213357aecf9b3534b4ce24ac40b3eeacea5f13258cc2ca60c62b0caccb4e47d1da4ed52e175e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
